### ISSUE TITLE
Question about "Filter" commands

### ISSUE THREAD

**Issue by enonimos** [ftwkoopmans/msdap#10]
Hello,
Thank you for contributing MS-DAP to the community, it is the most well thought out analysis/statistical pipeline I have used. And it supports so many formats!  

After using the software briefly, I did have a few questions.  For the "filter" commands, these appear to set a requirement that the # or fraction specified has to be present in "every" sample group, not "at least one" sample group?  The "every" filter would remove quant info for proteins that are not present in all samples. Is there any plans to implement this less restrictive filter?  Was the intention that the "differential detection Z-score" analysis would be used to "recover" these group-specific proteins?

As one other "feature request",  when using the "setup_contrasts" function, it would be useful to have the option to specify a different column (other than group) from the sample_metadata file for sourcing the sample groups for contrasts. For multi-parameter experiments, this would save time, not having to edit the "group" column when differential testing is evaluated as a function of different experiment factors.

Thanks in advance,
Todd

**Comment by ftwkoopmans** [comment]
> After using the software briefly, I did have a few questions. For the "filter" commands, these appear to set a requirement that the # or fraction specified has to be present in "every" sample group, not "at least one" sample group? The "every" filter would remove quant info for proteins that are not present in all samples.

That is correct, the reasoning is that in order to perform test statistics between groups A and B it's probably wise to use peptide reliably detected in both (with the set of statistical tests implemented in MS-DAP so far). This originates from working with the peptide-level models MSqRob and MS-EmpiRe. e.g. doing a test where you have very few / no values in one sample group using an algorithm like MS-EmpiRe makes little sense. Note that you can opt for "by contrast" filtering to maximise the number of available peptides when comparing groups A and B (e.g. if your datasets also has groups C and D, you probably don't care if the peptide was/not present in those groups when testing A-vs-B).

> Is there any plans to implement this less restrictive filter? 

We could probably introduce some more flexibility in the filtering, but it's important to keep it simple to use as well.

> Was the intention that the "differential detection Z-score" analysis would be used to "recover" these group-specific proteins?

Yea you can use these (crude) scores to rank proteins that have a strong difference in detection rates.


> As one other "feature request", when using the "setup_contrasts" function, it would be useful to have the option to specify a different column (other than group) from the sample_metadata file for sourcing the sample groups for contrasts. For multi-parameter experiments, this would save time, not having to edit the "group" column when differential testing is evaluated as a function of different experiment factors.

We experienced the same thing. Other users have also pointed out that it's currently hard to accomodate more complex experimental designs (e.g. continuous covariates). Haven't landed on a definite solution yet, but in future updates we'll be looking for improvements in this area.

**Comment by enonimos** [comment]
Thanks for the quick feedback, very helpful!
