### ISSUE TITLE
Technical replicates averaging before group comparation

### ISSUE THREAD

**Issue by DiQin2023** [ftwkoopmans/msdap#14]
Hi,
Thanks for the nice package! I have 2-3 technical replicates for each sample in my dataset, how can I make sure they are averaged before group comparison? Thanks!

**Comment by ftwkoopmans** [comment]
Perhaps you should account for the technical replicates in the statistical model instead of averaging values in the dataset (prior to statistical comparison of your experimental conditions). You can add random variables to the DEqMS and MSqRob linear regression models using the 'random_variables' parameter in the `setup_contrasts()` function. Example; `dataset = setup_contrasts(dataset, contrast_list = list(c("control","disease")), random_variables = "patient")`  (assuming that 'patient' is a column in your sample metadata & this "groups" your technical replicates / repeated measurements of the same individual). This would be the easiest solution, but I'm not 100% sure if that applies to your dataset, it kind of depends on your experimental design; please consult your lab's statistician.

If you want to go down the route of averaging the data between replicates; this is not a built-in MS-DAP feature. But here's an example of how you could do this;
1) usual MS-DAP workflow of preparing the input data; import dataset, fasta files and sample metadata
2) apply the `filter_dataset()` function to perform filtering & normalization
3) write some code that summarizes/collapses the dataset$peptides table (unfortunately, I don't have time to help you write this code atm)
4) apply the `dea()` function to perform statistics

**Comment by ftwkoopmans** [comment]
release 1.0.6 is now live and includes a function for merging technical replicates right after importing the data (i.e. prior to any filtering/normalizing/stats). After updating MS-DAP (instructions on main MS-DAP GitHub page), see help page for the new `merge_replicate_samples()` function (e.g. by issuing the R command `?merge_replicate_samples` , after installing the updated R package).

previous recommendations still apply though; for some datasets it's better to deal with replicate measurements in statistical modeling (please consult with your local statistician)

**Comment by DiQin2023** [comment]
Dear Frank,

Thanks for your reply and kind suggestions. I tried your first suggestion of treating the replicates as random variables but popped up too many differential proteins. I will definitely update to the new version and try this new function.
Thanks again for your amazing package, it's very handy and useful!

Best,
Di
________________________________
