### ISSUE TITLE
problem generating foldchange distribution plots in report

### ISSUE THREAD

**Issue by jd690764** [ftwkoopmans/msdap#25]
Hi,

I have a problem with the report generation - the peptide "within-group foldchange distributions" and protein "foldchange distribution" plots are not created properly, the actual data are missing. 

Trying to create them manually, e.g.:

msdap:::plot_foldchange_distribution_among_replicates(msf$peptides, msf$samples)

gives me errors like this:

Computation failed in `stat_density()`.
Caused by error in `precompute_bw()`:
! `bw` must be one of "nrd0", "nrd", "ucv", "bcv", "sj", "sj-ste", or "sj-dpi", not "SJ".
ℹ Did you mean "sj"?

When I change bw = 'SJ' to 'sj' in the ggplot call the correct plot is produced. 

Can you please look into this?

Thank you,
Janos

[r_session_info.txt](https://github.com/ftwkoopmans/msdap/files/15123145/r_session_info.txt)

**Comment by ftwkoopmans** [comment]
Thanks for reporting this issue. I'm working on a a new MS-DAP release that also includes a few other minor updates, it should be out soon(tm).

It seems that breaking changes in a recent ggplot release are the root cause; `bandwidth="SJ"` is no longer supported for density functions in ggplot.

Reproducing this issue;
in base R 4.2.1 , the stats::density function with parameter `bw="SJ"` works as intended; `plot(density(rnorm(1000), bw = "SJ"))`
when ggplot2 version 3.5 is installed, the following statement reproduces the error reported above; 
```
library(ggplot2)
ggplot(data.frame(x=rnorm(1000)), aes(x)) + stat_density(bw = "SJ")
```
in previous ggplot versions this used to work fine (i.e. we've been using this density bandwidth parameter in ggplot for years)

**Comment by jd690764** [comment]
Thank you - how soon do you expect the update?

**Comment by ftwkoopmans** [comment]
I'm currently testing the new update across various datasets and R versions. If no major issues come up the new release should go live sometime in the next few days

**Comment by ftwkoopmans** [comment]
the new release 1.0.7 is now live. Please update the R package and let me know if your issue has been resolved.

Run this R snippet in a clean R session (i.e. restart RStudio if it is running) to update
```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
```

**Comment by jd690764** [comment]
Yes, it's working now! Sorry for the delay and thank you for the quick fix!
Janos

**Comment by ftwkoopmans** [comment]
ok great, good luck with your analyses
