### ISSUE TITLE
Specific label name in volcano plots

### ISSUE THREAD

**Issue by lananh-ngn** [ftwkoopmans/msdap#3]
Dear developers, 
Thank you for this package. I would like to know if it would be possible to add an option to highlight specific labels in the generated volcano plots chosen by the user?
Thank you in advance.

**Comment by ftwkoopmans** [comment]
For the standard MS-DAP report PDF we simply plot labels for the topN proteins because this consistently generates useful plots regardless whether there are no significant hits, a few or hundreds (and before running the pipeline, one doesn't know how many or which proteins are significant of course).

I think your question fits a pretty common use-case of labeling some set of proteins-of-interest in the volcano plots, so I've updated MS-DAP such that you can now create volcano plots with various label styles after running the pipeline (see https://github.com/ftwkoopmans/msdap/releases/tag/1.0.1 ).

Make sure to update the MS-DAP R package
- close RStudio
- start new RStudio session
- install MS-DAP from github using this R code snippet;
```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
```

If all is well, you now have version 1.0.1 installed and you can apply below examples to your dataset (you can double-check the package version in RStudio at the bottom-right of the screen, tab 'Packages' > search for 'msdap' (without quotes))

The updated msdap::plot_volcano() function allows you to create plots similar to those shown in the report. But, importantly, you can use this only after you applied the MS-DAP pipeline using `analysis_quickstart()` because that function attaches the DEA results to the dataset object.

Below are various examples that show how to label specific sets of proteins and/or add your own ggplot labeling code. Note that you can always save these plots as PDF or SVG and import them as vector graphics into Adobe Illustrator or Libreoffice Draw to customize a bit for publication.

```
## Note that these examples assume that prior, the MS-DAP pipeline was successfully run using `dataset = analysis_quickstart(dataset, ...)`

# example 1: add protein-metadata to the DEA results (dataset$de_proteins), plotting the top 10 'best pvalue' hits while hardcoding the cutoffs for foldchange and Q-value
plot_list = msdap::plot_volcano(dataset$de_proteins %>% left_join(dataset$proteins), log2foldchange_threshold = 1, qvalue_threshold = 0.01, mtitle = "volcano, label top 10", label_mode = "topn_pvalue", label_target = 10, label_avoid_overlap = TRUE)
lapply(plot_list, "[[", "ggplot") # for each unique 'algo_de' in the input stats_de table, a list with a ggplot object and it's respective data

# example 2: analogous, but now show all significant proteins and disable "repelled labels" (instead, print protein labels just below each data point)
plot_list = msdap::plot_volcano(dataset$de_proteins %>% left_join(dataset$proteins), log2foldchange_threshold = 1, qvalue_threshold = 0.01, mtitle = "volcano, label all significant", label_mode = "signif", label_avoid_overlap = FALSE)
lapply(plot_list, "[[", "ggplot")

# example 3: show labels for some set of protein IDs. First line selects all proteins where symbol starts with GRIA or DLG (arbitrary example, either adapt the regex or use other filters/criteria to define a subset of protein_id from your dataset). Second line shows how to specify protein_id to be used as a label
pid_label = dataset$proteins %>% filter(grepl("^(GRIA|DLG)", gene_symbols_or_id, ignore.case=T)) %>% pull(protein_id)
plot_list = msdap::plot_volcano(dataset$de_proteins %>% left_join(dataset$proteins), log2foldchange_threshold = 1, qvalue_threshold = 0.01, mtitle = "volcano, label selected proteins", label_mode = "protein_id", label_target = pid_label, label_avoid_overlap = FALSE)
lapply(plot_list, "[[", "ggplot")

# example 4: plot all significant labels as before, then add custom labels for some subset of proteins (we here regex select some labels in the plot, you should adapt the regex to match some proteins in your dataset to make this work, but you can also further filter by other properties in the 'ggplot_data' tibble like the y-coordinate aka qvalue)
plot_list = msdap::plot_volcano(dataset$de_proteins %>% left_join(dataset$proteins), log2foldchange_threshold = 1, qvalue_threshold = 0.01, mtitle = "volcano, label all significant + custom labels", label_mode = "signif", label_avoid_overlap = FALSE)
l = plot_list[[1]]
l$ggplot + ggrepel::geom_text_repel(alpha=1, color="green", data = l$ggplot_data %>% filter(plottype %in% c("asis_lab", "lim_lab") & grepl("^(GRIA|DLG)", label, ignore.case = T)), segment.alpha = 0.3, min.segment.length = unit(0.25, 'lines'), vjust = 0.6, show.legend = FALSE, size = 2)
```

Please let me know if everything works out

**Comment by lananh-ngn** [comment]
Hello,
Thank you for precise answer. It helped a lot and it worked out perfectly fine. I have another question though. Is there any way to define the contrasts that we want for the volcano plots?
Thank you in advance!

**Comment by ftwkoopmans** [comment]
> Is there any way to define the contrasts that we want for the volcano plots?

Good question, above example assume there is just 1 contrast. The `msdap::plot_volcano()` function will create a plot for each DEA algorithm presented in the input table (it iterates over `unique(stats_de$algo_de)`) but does not iterate over contrasts.

So if your dataset / DEA results contains multiple contrasts you'll want to call `msdap::plot_volcano()`  for respective `dataset$de_proteins` subsets.

example;
```
contrasts = unique(dataset$de_proteins$contrast)
for(contr in contrasts) {
  # subset the DEA results for the current contrast
  tib_volcano = dataset$de_proteins %>% filter(contrast == contr) %>% left_join(dataset$proteins)

  # volcano plot function (compared to above example snippet, we now include the contrast in the title)
  plot_list = msdap::plot_volcano(tib_volcano, log2foldchange_threshold = 1, qvalue_threshold = 0.01, mtitle = paste(contr, "volcano, label top 10"), label_mode = "topn_pvalue", label_target = 10, label_avoid_overlap = TRUE)

  # grab ggplot objects and print plot
  ggplot_list = lapply(plot_list, "[[", "ggplot")
  for(p in ggplot_list) {
    print(p)
  }
}
```

ps. if you only want to plot a specific contrast, filter/subset `constrasts` in the line after `contrasts = unique(dataset$de_proteins$contrast)`
