### ISSUE TITLE
msqrob is returning error

### ISSUE THREAD

**Issue by jd690764** [ftwkoopmans/msdap#36]
Hi,

It seems every time (with different datasets) I try msqrob as the dea_algorithm in analysis_quickstart I get this error:

info: msqrob linear regression formulas (these are prioritized. eg; if a model fit fails due to lack of data, the next formula is used); expression ~ (1 | condition) + (1 | sample_id) + (1 | peptide_id)  ,  expression ~ (1 | condition)
warning: an error occurred in contrast: n vs t during the execution of DEA function 'msqrob'
warning: In argument: `sigma_post = sigma`.
language mutate(df, sigma_post = sigma, df_prior = 0, sigma_prior = 0)

I am using the version=1.1.2.  I did use this method in earlier versions with success in the past.

I can send a dataset to test if you need it to reproduce the error.

Thank you,
Janos

**Comment by ftwkoopmans** [comment]
If you could share the dataset and the version of R packages installed on your system, I'll investigate what is causing these issues. 

A) please share your operating system, R version, MS-DAP package version, etc. by executing the following R code (in a new R session) and copy/pasting the output.

```
library(msdap)
devtools::session_info()
```

B) upload your dataset (via Dropbox/wetransfer/etc) and also include the full MS-DAP console output instead of the small snippet you shared previously so I can check for upstream errors / info messages.

My email address is listed as corresponding author in the MS-DAP manuscript)

**Comment by ftwkoopmans** [comment]
Thanks for sharing your dataset. After creating a fresh R installation that matches your R version (that is listed in the output from `session_info()` that you provided) I was finally able to reproduce the error after extensive debugging. The root issue turned out to be an obscure incompatibility between the `lme4` and `Matrix` R packages... it seems one cannot get a proper installation of both these packages when using R 4.3 at the moment while using the typical R functions/workflow to install packages. So the issue is not with any code in MS-DAP, there is an incompatibility with R packages installed on your system that needs to be resolved.

For reference, the issue has been reported and discussed before; https://stackoverflow.com/a/77532685

A fix that worked on my system was to:
- First, remove the lme4 and Matrix packages
  - in bottom-right RStudio pane, tab "Packages"
  - search for Matrix
  - click cross symbol to remove
  - check: if all is well, the Matrix R package is now removed from your R installation
  - repeat the above steps for the lme4 package
- Next, install specific versions of these packages that are compatible and work with R version 4.3
```
install.packages("https://cran.r-project.org/src/contrib/Archive/Matrix/Matrix_1.6-5.tar.gz")
install.packages("https://cran.r-project.org/src/contrib/Archive/lme4/lme4_1.1-35.3.tar.gz")
```

---

If you run into errors removing/installing these packages, try to run RStudio "as Administrator" to ensure you have the rights to remove/write files in these folders.

ps. for other MS-DAP users reading this; these issues should not occur on a fresh installation of the latest version of R (4.4.0 ~ 4.4.1). So a fresh installation of the latest R and RTools, followed by MS-DAP installation (per instructions on the main page of this GitHub repo) should yield compatible versions of lme4 and Matrix.

**Comment by jd690764** [comment]
After doing the downgrades as you suggested, it works great now! Thank you
very much for tracking it down! (Also, thank you for fixing #35!)

Janos

**Comment by ftwkoopmans** [comment]
Ok great, I'm glad it all worked out. Good luck with your analyses!
