### ISSUE TITLE
Request: Use data filtered by group for abundance and DEA/Differential Detection

### ISSUE THREAD

**Issue by jmvarberg** [ftwkoopmans/msdap#42]
Hello,

First, thank you for this wonderful package! I've been testing different workflows and have a question regarding peptide filtering/feature selection and how it is used for downstream normalization/roll-up to protein abundances and differential detection. 

In the current version, applying the "filter by contrast" requires peptides to pass number/fraction of samples filtering in BOTH groups. As a result, any peptides that would otherwise be retained by using the "filter by group" approach are removed and are not used for normalization or protein roll-up. It seems like if those peptides passed all filtering criteria within a group, that it would make sense to retain them for normalization and roll-up? 

In trying to make this work, I see that the function `get_column_intensity()` does not include an option to use the "intensity_by_group" column, even if it exists after performing filtering by group. So, if you have performed filtering by group, the fold-change values (for example for DEqMS results) are computed using the protein abundance values from the "input data as is". Modifying the `get_column_intensity()` function to include an option for filter by group seemed to work, allowing the downstream DEA to use the peptides filtered by group values (although a warning message applies informing on the number of peptides/proteins that were removed prior to DEA - this seems to be fine/expected behavior).

I'm curious if there was a rational for not including the option to do DEA/Differential detection on the peptides filtered by group? If not, supporting a workflow that would 1) filter peptides within individual groups, 2) perform normalization/roll-up, 3) extract the samples for each desired contrast, 4) use the features that pass the required number of values per group for DEA and then 5) use the remaining features that pass filters for Differential Detection, would be of interest. This would ensure that as much information as possible is used to derive abundance values while also ensuring that these values are also used for fold-change calculations for DE/DD.

Thank you!

**Comment by ftwkoopmans** [comment]
First, to simplify this discussion: the "differential detection" stuff is completely separated from DEA, i.e. the filtering and normalization settings (of intensity values) are irrelevant because the differential detection function uses the number of detected peptide counts per protein per sample based on the input data as-is.

Regarding DEA: the rationale is that we want to perform statistics based on the subset of peptides that is "reliably detected" (i.e. in x% of the replicates). The MSqRob and MS-EmpiRe models compute stats on the peptide-level and they need sufficient datapoints to do so (i.e. these models assume MCAR, missing completely at random). And indeed, we find that the vast majority of MS-DAP users and use-cases want to 1) work mainly with the DEA results (differential detection is a less reliable, supplementary metric) and 2) focus on the subset of consistently quantified peptides (e.g. in at least 60% of replicates and at least 2 peptides per protein) to maximize the actual/empirical true positive rates.

If you're a bioinformatician who doesn't mind programming a bit, you can write your own filtering code and then apply the `dea()` function. Typically you'd follow these steps;

0. importantly, we here assume that prior to these steps you have only imported the dataset/fasta/sample data
1. copy the peptide intensity column over into a column that is normally used to store the "all group" filtering results
2. set values to NA for peptide*sample combinations that do not pass your filtering rules
3. apply the normalization function to your "filtered data"
4. apply DEA


Quickly typing out approx code in my browser, something like;

0. 
```
library(msdap)
dataset = import_dataset_diann(...)
dataset = import_fasta(...)
dataset = import_sample_metadata(...)
```
1. `dataset$peptides$intensity_all_group = dataset$peptides$intensity_all_group`
2. count the number of observations per peptide per sample group, then apply some filtering. Here assuming you have a simple dataset with conditions "A" and "B" (as described in the "group" column of the sample metadata table);
```
x = dataset$peptides |> select(peptide_id, sample_id, intensity) |> filter(!is.na(intensity)) |> left_join(dataset$samples |> select(sample_id, group))
y = x |> count(peptide_id, group) # count in how many samples a peptide was found, per group
z = y |> filter(n >= 5) # retain peptide*group combo's that have at least N observations in either of the groups
pepid_retain = z |> distinct(peptide_id) |> pull()
dataset$peptides$intensity_all_group[ ! dataset$peptides$peptide_id %in% pepid_retain] = NA
# if there are samples you want to ignore/remove, you can analogously set these to NA; dataset$peptides$intensity_all_group[ ! dataset$peptides$sample_id %in% smplid_retain] = NA
```
3. normalize this specific column
```
dataset = normalize_peptide_intensity_column(
  dataset,
  col_intensity = "intensity_all_group",
  norm_algorithm = c("mwmb", "modebetween_protein"),
  rollup_algorithm = "maxlfq"
)
```
4. apply DEA. 
```
# still have to define a contrast, this tells the DEA function which sets of samples to compare
dataset = add_contrast(dataset, "group", values_condition1="A", values_condition2="B")
# call the DEA function; it'll automatically use the "intensity_all_group" column
dataset = dea(dataset, dea_algorithm = "deqms)
```

You can find the DEA results in table `dataset$de_proteins` afterwards.

Note that MS-DAP will always apply 1 hardcoded layer of filtering right before calling the packages/code that implements the actual statistical tests. There must be at least 3 datapoints in each condition for each protein when using ebayes/deqms (these functions cannot estimate variation and t-statistics with fewer values). Similarly, msqrob/msempire need at least 3 values per peptide on both sides of the contrast to compute stats. But at least now you can follow the above code to have the flexibility to require peptides or proteins to be observed in at least 6/10 replicates in one condition and 3/10 in the other.

**Comment by jmvarberg** [comment]
Thank you for the quick response - I understand the requirement for a minimum of 3 observations in both groups for the statistical comparisons for DEA, and the filter-by-contrast handles this nicely. Perhaps the workflow below will better illustrate the main part of my question. 

I tried using the following approach to filter the peptides using “by_group = TRUE”, then taking those filtered, normalized peptide abundance values to derive the protein-level abundance values, followed by DEA:

```
library(msdap)
dataset = import_dataset_spectronaut(...)
dataset = import_fasta(...)
dataset = import_sample_metadata(...)
dataset = setup_contrasts(...)

#now, filter the peptides using the "filter by group" method
dataset = filter_dataset(dataset, filter_min_detect = 3, filter_min_peptide_per_prot = 2, 
                         norm_algorithm = c("vsn", "modebetween_protein"), 
                         rollup_algorithm = "maxlfq", 
                         by_group = TRUE, 
                         all_group=F, 
                         by_contrast=F)
```
We should now have applied the filtering and normalization at the peptide level applying the criteria within individual groups.

If we then run:

```
dataset <- dea(dataset, dea_algorithm = "deqms", rollup_algorithm = "maxlfq")
```
What we see is that when it performs the DEA, it uses the “input data as is” intensity values, instead of the “intensity_by_group” values. 

By modifying the `get_column_intensity()` function as below:

```
#allow for selection of intensity by group column
get_column_intensity = function(peptides, contr_lbl = NA) {
    ref = c("filter by contrast" = paste0("intensity_", contr_lbl),
            "filter by group" = "intensity_by_group", #modified line
            "global data filter" = "intensity_all_group",
            "custom filtering and normalization" = "intensity_norm",
            "input data as-is" = "intensity")
    return(ref[ref %in% colnames(peptides)][1])
}
```

and running the dea() function again, it correctly uses the “intensity_by_group” values. A warning is returned when dea() runs saying that some proteins were removed prior to the DEA function, which makes sense as it is then applying the filtering to keep features with sufficient observations to do the stats testing. The benefit then of using the filter by group is to use a potentially larger set of peptides that passed filtering within individual groups to perform normalization and roll-up to derive abundance values.

Does this workflow seem reasonable? Is there any reason that the "filter by group" option was not included in `get_column_intensity()`? Just wanting to make sure there's not a reason why the above approach would not be valid.

Thanks!

**Comment by ftwkoopmans** [comment]
In the example that you gave, you could also run `dataset$peptides$intensity_all_group = dataset$peptides$intensity_by_group` right before the `dea()` call; then you wouldn't have to overwrite the `get_column_intensity()` function. Or write your desired peptide filtering results into `dataset$peptides$intensity_norm` (should be the same from reading the code, just haven't tested, I'm swamped in deadlines atm so have to time to follow any of this up)

> Is there any reason that the "filter by group" option was not included in get_column_intensity()?

It's simply because this is not a recommended workflow, never was implemented. And I'm hesitant to just update this function without triple-checking that no workflows will break for existing users. So for now you could just apply whatever filtering you want and then overwrite the `dataset$peptides$intensity_all_group` column as suggested above and it's done.

**Comment by jmvarberg** [comment]
Great thank you for clarifying!
