### ISSUE TITLE
integer overflow error / working with huge datasets

### ISSUE THREAD

**Issue by fcgportal** [ftwkoopmans/msdap#7]
Hi there, thank you for developing this tool! 
Everything went smoothly when I input a small toy dataset, but when I input a large psm.tsv which came into a 404,053,022 * 10 peptides tibble, it said integer overflow error. 

> dataset = filter_dataset(dataset, filter_min_detect = 1, filter_min_peptide_per_prot = 1, norm_algorithm = c("vsn", "modebetween_protein"), rollup_algorithm = "maxlfq", by_group = T, all_group = F, by_contrast = F)
Error in `vec_init()`:
! `n` must be a single number, not an integer `NA`.
Run `rlang::last_error()` to see where the error occurred.
Warning message:
In nrow * ncol : NAs produced by integer overflow

Would you please help me with it?
Thanks again!

**Comment by ftwkoopmans** [comment]
I haven't seen that before, most likely because the datasets we've tested with are at most a few hundred samples.

If you're able to share the dataset with me I'll try to reproduce this error and then find a solution / workaround for huge datasets. Not sure how straight forward the solution is until I debug; perhaps this'll require substantial work, let's find out.

(if you can send me a download link for the respective MS-DAP input files by email that would be great, my address is included as 'corresponding author' in the publication @ https://doi.org/10.1021/acs.jproteome.2c00513 )

**Comment by fcgportal** [comment]
> 

Thank you so much for your help, and I've sent the file via email.

**Comment by ftwkoopmans** [comment]
We're working on better scalability for MS-DAP and aim to enable analyses of huge datasets even on typical workstation computers in a future MS-DAP release.

In the meanwhile, we attached some code as an intermediate solution that will enable protein-level analysis of very large datasets by using simplified and more RAM efficient implementations of peptide-level filtering, peptide-to-protein rollup and DEqMS differential expression statistics. We've done preliminary tests with a dataset of 4000+ DDA samples on a 64GB RAM workstation running Windows 10. Also included are example code for PCA and volcano plots in this workflow. 

Please note that this is temporary solution, beta-version code that could use some more testing and is only intended to be used on very large datasets where typical MS-DAP workflows don't fit into RAM. Please test extensively before using in 'production' and reach out if you encounter any bugs


[msdap_lowram_beta_2022-02-18.zip](https://github.com/ftwkoopmans/msdap/files/10774001/msdap_lowram_beta_2022-02-18.zip)

**Comment by fcgportal** [comment]
> We're working on better scalability for MS-DAP and aim to enable analyses of huge datasets even on typical workstation computers in a future MS-DAP release.
> 
> In the meanwhile, we attached some code as an intermediate solution that will enable protein-level analysis of very large datasets by using simplified and more RAM efficient implementations of peptide-level filtering, peptide-to-protein rollup and DEqMS differential expression statistics. We've done preliminary tests with a dataset of 4000+ DDA samples on a 64GB RAM workstation running Windows 10. Also included are example code for PCA and volcano plots in this workflow.
> 
> Please note that this is temporary solution, beta-version code that could use some more testing and is only intended to be used on very large datasets where typical MS-DAP workflows don't fit into RAM. Please test extensively before using in 'production' and reach out if you encounter any bugs
> 
> [msdap_lowram_beta_2022-02-18.zip](https://github.com/ftwkoopmans/msdap/files/10774001/msdap_lowram_beta_2022-02-18.zip)

Thank you so much, Frank. beta-version works very well for my data.

**Comment by ftwkoopmans** [comment]
minor update;
- added "by_group" filtering
- explicitly remove peptide*sample values for 'exclude' samples

Please note that you have to first load the MS-DAP R package `library(msdap)`, and then `source()` the attached script with low RAM helper functions (as demonstrated in the attached example script). The order matters, otherwise you might encounter errors like `"eset_proteins ExpressionSet fData must be a data.frame that contains column 'protein_id'"`. So when preparing to analyze huge datasets with this approach, first try to follow the example verbatim.

[msdap_lowram_beta_2022-03-05.zip](https://github.com/ftwkoopmans/msdap/files/10891781/msdap_lowram_beta_2022-03-05.zip)
